name: My workflow

on:
  workflow_run:
    types: ["manual"]

jobs:
  build:
    steps:
      - name: Check for tag parameter
        if: env.TAG
        run: echo "Tag used: ${{ env.TAG }}"
      # other steps based on the presence of TAG...
