name: My Workflow

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for deployment'
        required: true
      environment:
        description: 'Environment for deployment'
        required: true
        type: choice
        options:
            - LOCAL
            - DEV
            - UAT
            - PPE

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: check
      run: |
        project_name=${{ inputs.tag }}
        echo "Deploying tag: "${project_name%$-*}
        echo "To environment: ${{ inputs.environment }}"
        echo "here are the details : " ${{ github.ref }}
        echo "Selected Branch" ${{ github.ref_name }}
        echo "Selected type "${{ github.ref_type }}
    - name: tag-check
      run: |
        if [[ $GITHUB_SHA =~ ^refs/tags/(.*) ]]; then
          echo "Tag used: $BASH_REMATCH[1]"
        else
          echo "Not triggered by a tag"
        fi

