name: My Workflow

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for deployment'
        required: true
      environment:
        description: 'Environment for deployment'
        required: true
        options:
            - LOCAL
            - DEV
            - UAT
            - PPE

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy
      run: |
        echo "Deploying tag: ${{ inputs.tag | grep -oE '^[^-]+') }}"
        echo "To environment: ${{ inputs.environment }}"
