name: My Workflow

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for deployment'
        required: true
      environment:
        description: 'Environment for deployment'
        required: true
        type: choice
        options:
            - LOCAL
            - DEV
            - UAT
            - PPE

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy
      run: |
        project_name=$(echo ${{ inputs.tag }} | cut -d'-' -f1)
        echo "Deploying tag: $project_name"
        echo "To environment: ${{ inputs.environment }}"
        echo "Selected Branch" ${{ github.ref_name }}
        echo "Selected type "${{ github.ref_type }}
