name: My Workflow

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for deployment'
        required: true
        default: 'v1.0.0' # You can set a default value or remove it
      environment:
        description: 'Environment for deployment'
        required: true
        default: 'production' # You can set a default value or remove it

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy
      run: |
        echo "Deploying tag: ${{ inputs.tag }}"
        echo "To environment: ${{ inputs.environment }}"
