name: Manual Trigger

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for deployment'
        required: true
        default: 'v1.0.0' # You can set a default value or remove it
      environment:
        description: 'Environment for deployment'
        required: true
        default: 'production' # You can set a default value or remove it

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger My Workflow
      uses: actions/workflow-dispatch@v2
      with:
        workflow: 'My Workflow'
        inputs: |
          {
            "tag": "${{ github.event.inputs.tag }}",
            "environment": "${{ github.event.inputs.environment }}"
          }
